{% set version = "6.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mclust/mclust_{{ version }}.tar.gz
  sha256: 5df469cc4aa2e86bf4282cb83eaa53f90f671aa6567e8778331bf8c1666f9055

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('mclust')"           # [not win]
    - "\"%R%\" -e \"library('mclust')\""  # [win]

about:
  home: https://mclust-org.github.io/mclust/
  license: GPL-2.0-or-later
  summary: Gaussian finite mixture models fitted via EM algorithm for model-based clustering, classification, and density estimation, including Bayesian regularization, dimension reduction for visualisation, and resampling-based inference.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mclust
# Version: 5.4.5
# Date: 2019-07-07
# Title: Gaussian Mixture Modelling for Model-Based Clustering, Classification, and Density Estimation
# Description: Gaussian finite mixture models fitted via EM algorithm for model-based clustering, classification, and density estimation, including Bayesian regularization, dimension reduction for visualisation, and resampling-based inference.
# Authors@R: c(person("Chris", "Fraley", role = "aut"), person("Adrian E.", "Raftery", role = "aut", comment = c(ORCID = "0000-0002-6589-301X")), person("Luca", "Scrucca", role = c("aut", "cre"), email = "luca.scrucca@unipg.it", comment = c(ORCID = "0000-0003-3826-0484")), person("Thomas Brendan", "Murphy", role = "ctb", comment = c(ORCID = "0000-0002-5668-7046")), person("Michael", "Fop", role = "ctb", comment = c(ORCID = "0000-0003-3936-2757")))
# Depends: R (>= 3.0)
# Imports: stats, utils, graphics, grDevices
# Suggests: knitr (>= 1.12), rmarkdown (>= 0.9), mix (>= 1.0), geometry (>= 0.3-6), MASS
# License: GPL (>= 2)
# URL: https://mclust-org.github.io/mclust/
# VignetteBuilder: knitr
# Repository: CRAN
# ByteCompile: true
# LazyData: yes
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-07-07 15:54:41 UTC; luca
# Author: Chris Fraley [aut], Adrian E. Raftery [aut] (<https://orcid.org/0000-0002-6589-301X>), Luca Scrucca [aut, cre] (<https://orcid.org/0000-0003-3826-0484>), Thomas Brendan Murphy [ctb] (<https://orcid.org/0000-0002-5668-7046>), Michael Fop [ctb] (<https://orcid.org/0000-0003-3936-2757>)
# Maintainer: Luca Scrucca <luca.scrucca@unipg.it>
# Date/Publication: 2019-07-08 18:51:30 UTC
