{% set version = "5.4.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mclust
  version: {{ version|replace("-", "_") }}

source:
  fn: mclust_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mclust_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mclust/mclust_{{ version }}.tar.gz
  sha256: c43e19d3df0806c522520260d4de841314548baf91a099a6905bf885a82594ed

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('mclust')"  # [not win]
    - "\"%R%\" -e \"library('mclust')\""  # [win]

about:
  home: http://www.stat.washington.edu/mclust/
  license: GPL (>= 2)
  summary: Gaussian finite mixture models fitted via EM algorithm for model-based clustering,
    classification, and density estimation, including Bayesian regularization, dimension
    reduction for visualisation, and resampling-based inference.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
