travis:
  secure:
    BINSTAR_TOKEN: MWlBDeT8CSxdOyVkfsVuIZyTiA1Fk0HG8KPrPO0fmoYCJ1Jd9y7ppg2X6OkE8klOtkm/P3RlNLkxoiZ6cE9/q/fr/yvxDyjtcV/a6BYNTU9GdkW1cUes5sO/Bi59z1qdaG0mM/uXYLm+qUfAgxQ/B7RNstKKduyOGETv6QDf5nj7kAvJxHlUT6h0x/MzFNYquIRC+S24u8crUlhbVQyLvZauiiR1K5ia5mtU3tsj5nL+Ku1rNs8Xk9Z9FfHp1QWZchJb3mHrSHXsadLVrQ/IJT5w1qTbomrxPcMfe3Jx7T6WVn5PkzoQTJ002+xt/CFsQmg3ygsH8MyM90zNYJwavM+3VRQPdCsq6YQh67n8Reo2FgLLCsovBgBJ5mBagV0NH1tsH9Wg8d0p4rgGyIddiw4JXmFPGbDhrSj5llmL89FLGkwTXVepFqaxq6MmPOVRo6s7Plll4Q1xKC/Utp9srVYZ9LpSgxtl75YBrDNHqx6JuBLhpEVWeKFVv7zB7RWdJKz4aRRVWu+TbTxoyxzXc5nNJQTdyFzaV6ovBual5eABEdTrLeyrCjvbbbt1+A6qHMavGE52UnBQSPnfiMDK7GDfBrMM3qLRe0FaztjTAaNNsT/E7HeQUvHmPJBg+zEnPeIbQne3CoFofaTPsCFtMwRT6rXNE6qcIa7eF9YJmXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
